image: $CI_DOCKER_REGISTRY/esp32-toolchain

variables:
  # GIT_STRATEGY - use an option in "CI / CD Settings" - "General pipelines"
  GIT_SUBMODULE_STRATEGY: recursive
  DESTDIR: ${CI_PROJECT_DIR}/dist

x86_64-linux-gnu:
  tags: [ "build", "amd64" ]
  artifacts:
    paths:
      - ${DESTDIR}
      - "*.a"
    expire_in: 1 week
  script:
    - make install DESTDIR=${DESTDIR} PLATFORM=linux
